version: '3'
services:
  php-app:
    build: .
    ports:
      - "8080:88"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csv-reader
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3307:3307"
